name = "sikaku-api"
compatibility_date = "2023-12-01"
main = "src/index.ts"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "sikaku_database"
database_id = "6a721ef3-fadf-4e0c-a5f0-db5b5ed1896e"
migrations_dir = "drizzle/migrations"

# [ai]
# binding = "AI"
